# Reusable workflow for all MacOS builds
name: Fuse Utils For MacOS
run-name: Build Fuse Utils for MacOS / ${{ github.actor }} /

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      dependencies:
        type: string
        required: false
        default: ""
      configure_params:
        type: string
        required: false
        default: ""

jobs:
  build:
    name: Build Utils
    runs-on: macos-latest
    timeout-minutes: 15
    defaults:
      run:
        shell: bash
    steps:
      - name: (1) Prepare environment
        run: |
          echo -n "Current directory: "
          pwd
          ls -la

      - name: (2) Check out repository code
        uses: actions/checkout@v3

      - name: (3) Install dependencies
        run: |
          echo "Inspect if brew installed .."
          brew doctor || true
          
          echo "Upgrade bash (fix |& ) .."
          brew install bash
          which -a bash
          bash --version
          sudo sh -c 'echo /usr/local/bin/bash >> /etc/shells'
          
          echo "Installing dependencies .."
          brew install \
            automake \
            audiofile \
            bzip2 \
            libgcrypt \
            glib \
            libxml2 \
            ${{ inputs.dependencies }}
          autoreconf -i

      - name: (4) Download libspectrum artefact
        uses: actions/download-artifact@v3
        with:
          name: libspectrum-installed-macos-fuse-utils
          path: libspectrum

      - name: (5) Install libspectrum from artefact
        run: |
          # Extract (-x) files into /usr/local
          sudo tar --directory / -xvf libspectrum/libspectrum-installed-macos.tar
          echo "Done"

      - name: (6) Autogen.sh
        run: ./autogen.sh

      - name: (7) Configure for MacOS
        run: |
          ./configure ${{ inputs.configure_params }} \
          |& tee ./configure.out

      - name: (8) Verify output from configure
        # Most of the tested strings are common for all MacOS builds
        run: |          
          .github/scripts/in_config.sh "The Fuse utils are ready to be compiled"
          .github/scripts/in_config.sh "zlib support: yes"
          .github/scripts/in_config.sh "libjpeg support: yes"
          .github/scripts/in_config.sh "libpng support: yes"
          .github/scripts/in_config.sh "libgcrypt support: yes"
          .github/scripts/in_config.sh "libaudiofile support: yes"
          .github/scripts/in_config.sh "libspectrum's internal GLib replacement: no"

      - name: (9) Make
        run: make

      - name: (10) Install
        run: sudo make install

      - name: (11) Finish
        run: |
          echo "🍏 Finishing with status ${{ job.status }}."
