name: Fuse-Utils Linux Build
run-name: Build and test Fuse-Utils for Linux / ${{ github.actor }} /
on: [push]
jobs:
  build:
    name: Build Fuse-Utils for Linux
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: (1) Prepare git
        run: |
          echo "Not needed in this build"

      - name: (2) Check out repository code
        uses: actions/checkout@v3

      - name: (3) Install dependencies
        run: |
          echo "Installing dependencies .."
          sudo apt install -y libspectrum

      - name: (4) Autogen.sh
        run: |
          echo "Running autogen.sh .."
          ./autogen.sh

      - name: (5) Configure for linux (real glib)
        run: |
          echo "Running configure .."
          ./configure | tee ./configure.out

      - name: (6) Verify output from configure
        run: |
          cd ${GITHUB_WORKSPACE}/.github/scripts/
          ./in_config.sh "The Fuse utils are ready to be compiled"
          ./in_config.sh "zlib support: yes"
          ./in_config.sh "libjpeg support: yes"
          ./in_config.sh "libpng support: yes"
          ./in_config.sh "libgcrypt support: yes"
          ./in_config.sh "libaudiofile support: yes"
          ./in_config.sh "Internal GLib replacement: no"

      - name: (7) Make
        run: |
          echo "Running make .."
          make

      - name: (8) Install (+sudo)
        run: |
          echo "Running make install .."
          sudo make install

      - name: (9) Run tests
        run: |
          echo "Bulding and running tests .."
          make check

      - name: (10) Upload generated files
        uses: actions/upload-artifact@v3
        with: 
          name: fuse-utils-linux
          path: |
            README

      - name: (11) Finish
        run: |
          echo "🍏 Finishing with status ${{ job.status }}."
